import { Package } from '@/types';

export const defaultPackages: Package[] = [
  // Verizon - Monthly Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'vz-basic-5g-month',
    carrier: 'verizon',
    name: 'Basic 5G',
    price: 23,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'vz-5g-start-month',
    carrier: 'verizon',
    name: '5G Start',
    price: 24,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '5GB hotspot', 'No contract'],
  },
  {
    id: 'vz-5g-play-month',
    carrier: 'verizon',
    name: '5G Play More',
    price: 26,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '25GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '25GB hotspot', 'Premium network access', 'Disney+, Hulu, ESPN+ included', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'vz-5g-do-more-month',
    carrier: 'verizon',
    name: '5G Do More',
    price: 27,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '30GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '30GB hotspot', 'Premium network access', '50% off connected devices', 'No contract'],
  },
  {
    id: 'vz-5g-pro-month',
    carrier: 'verizon',
    name: '5G Pro',
    price: 29,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '40GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '40GB hotspot', 'Premium network access', 'Priority data', 'No contract'],
  },
  {
    id: 'vz-5g-get-more-month',
    carrier: 'verizon',
    name: '5G Get More',
    price: 30,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '50GB hotspot', 'Premium network access', 'Priority data', 'Disney+, Hulu, ESPN+ included', 'Apple Music included', 'Premium streaming', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'vz-5g-premium-month',
    carrier: 'verizon',
    name: '5G Premium',
    price: 53,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '75GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '75GB hotspot', '5G Ultra Wideband speeds', 'Premium network priority', 'All streaming services', 'International roaming', 'No contract'],
  },
  {
    id: 'vz-5g-ultra-month',
    carrier: 'verizon',
    name: '5G Ultra',
    price: 54,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '100GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '100GB hotspot', '5G Ultra Wideband speeds', 'Maximum network priority', 'All streaming services', 'International roaming', 'No contract'],
  },
  {
    id: 'vz-5g-max-month',
    carrier: 'verizon',
    name: '5G Max',
    price: 56,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '150GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '150GB hotspot', '5G Ultra Wideband speeds', 'Ultra-fast speeds', 'Maximum network priority', 'All streaming services', 'International roaming', 'Premium network priority', 'No contract'],
    badge: 'PREMIUM',
  },
  
  // Verizon - Annual Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt)
  {
    id: 'vz-basic-5g-year',
    carrier: 'verizon',
    name: 'Basic 5G (Annual)',
    price: 252,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', 'No contract', 'Save $252/year'],
  },
  {
    id: 'vz-5g-start-year',
    carrier: 'verizon',
    name: '5G Start (Annual)',
    price: 288,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', 'HD video streaming', '5GB hotspot', 'Unlimited talk & text', 'No contract', 'Save $288/year'],
  },
  {
    id: 'vz-5g-play-year',
    carrier: 'verizon',
    name: '5G Play More (Annual)',
    price: 312,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '25GB',
    features: ['Unlimited 5G data', 'Premium network access', 'Disney+, Hulu, ESPN+ included', '25GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $312/year'],
  },
  {
    id: 'vz-5g-get-more-year',
    carrier: 'verizon',
    name: '5G Get More (Annual)',
    price: 360,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited 5G data', '50GB hotspot', 'Disney+, Hulu, ESPN+ included', 'Apple Music included', 'Premium streaming', 'HD/4K video', 'Unlimited talk & text', 'No contract', 'Save $360/year'],
    badge: 'BEST VALUE',
  },

  // AT&T - Monthly Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt)
  {
    id: 'att-basic-month',
    carrier: 'att',
    name: 'Basic Plan',
    price: 18,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'att-unlimited-starter-month',
    carrier: 'att',
    name: 'Unlimited Starter',
    price: 19,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '5GB hotspot', 'No contract'],
  },
  {
    id: 'att-value-plus-month',
    carrier: 'att',
    name: 'Value Plus',
    price: 20,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '3GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '3GB hotspot', 'No contract'],
  },
  {
    id: 'att-unlimited-extra-month',
    carrier: 'att',
    name: 'Unlimited Extra',
    price: 22,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '15GB hotspot', 'Premium network access', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'att-unlimited-pro-month',
    carrier: 'att',
    name: 'Unlimited Pro',
    price: 26,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '30GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '30GB hotspot', 'Premium network access', 'Priority data', 'No contract'],
  },
  {
    id: 'att-unlimited-elite-month',
    carrier: 'att',
    name: 'Unlimited Elite',
    price: 27,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '40GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '40GB hotspot', 'Premium network access', 'Priority data', 'HBO Max included', 'Premium streaming', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'att-unlimited-max-month',
    carrier: 'att',
    name: 'Unlimited Max',
    price: 50,
    period: 'month',
    data: 'Unlimited',
    speed: '5G+',
    hotspot: '60GB',
    features: ['Unlimited 5G+ data', '4K video', 'Unlimited talk & text', '60GB hotspot', '5G+ speeds available', 'Premium network priority', 'HBO Max + Netflix', 'International roaming', 'No contract'],
  },
  {
    id: 'att-unlimited-ultra-month',
    carrier: 'att',
    name: 'Unlimited Ultra',
    price: 53,
    period: 'month',
    data: 'Unlimited',
    speed: '5G+',
    hotspot: '100GB',
    features: ['Unlimited 5G+ data', '4K video', 'Unlimited talk & text', '100GB hotspot', '5G+ Ultra speeds', 'Priority network access', 'HBO Max + Netflix', 'International roaming', 'No contract'],
  },
  {
    id: 'att-unlimited-premium-month',
    carrier: 'att',
    name: 'Unlimited Premium',
    price: 55,
    period: 'month',
    data: 'Unlimited',
    speed: '5G+',
    hotspot: '150GB',
    features: ['Unlimited 5G+ data', '4K video', 'Unlimited talk & text', '150GB hotspot', '5G+ Ultra speeds', 'Maximum network priority', 'All streaming services', 'HBO Max + Netflix', 'International roaming', 'No contract'],
    badge: 'PREMIUM',
  },
  
  // AT&T - Annual Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt)
  {
    id: 'att-value-plus-year',
    carrier: 'att',
    name: 'Value Plus (Annual)',
    price: 240,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '3GB',
    features: ['Unlimited 5G data', '3GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $240/year'],
  },
  {
    id: 'att-unlimited-starter-year',
    carrier: 'att',
    name: 'Unlimited Starter (Annual)',
    price: 228,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', '5GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $228/year'],
  },
  {
    id: 'att-unlimited-extra-year',
    carrier: 'att',
    name: 'Unlimited Extra (Annual)',
    price: 264,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', '15GB hotspot', 'Premium network access', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $264/year'],
  },
  {
    id: 'att-unlimited-elite-year',
    carrier: 'att',
    name: 'Unlimited Elite (Annual)',
    price: 300,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '40GB',
    features: ['Unlimited 5G data', '40GB hotspot', 'HBO Max included', 'Premium streaming', 'HD/4K video', 'Unlimited talk & text', 'No contract', 'Save $300/year'],
    badge: 'BEST VALUE',
  },

  // T-Mobile - Monthly Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt)
  {
    id: 'tm-basic-month',
    carrier: 'tmobile',
    name: 'Basic 5G',
    price: 21,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'tm-essentials-month',
    carrier: 'tmobile',
    name: 'Essentials',
    price: 23,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '3GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '3GB hotspot', 'No contract'],
  },
  {
    id: 'tm-magenta-month',
    carrier: 'tmobile',
    name: 'Magenta',
    price: 24,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '5GB hotspot', 'Netflix Basic included', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'tm-magenta-plus-month',
    carrier: 'tmobile',
    name: 'Magenta Plus',
    price: 26,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '20GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '20GB hotspot', 'Netflix Basic included', 'Premium network access', 'No contract'],
  },
  {
    id: 'tm-magenta-max-month',
    carrier: 'tmobile',
    name: 'Magenta Max',
    price: 28,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '40GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '40GB hotspot', 'Premium network access', 'Netflix Standard included', 'Premium streaming', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'tm-magenta-ultra-month',
    carrier: 'tmobile',
    name: 'Magenta Ultra',
    price: 51,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '60GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '60GB hotspot', '5G Ultra Capacity speeds', 'Premium network priority', 'Netflix Premium + Apple TV+', 'International roaming', 'No contract'],
  },
  {
    id: 'tm-magenta-extreme-month',
    carrier: 'tmobile',
    name: 'Magenta Extreme',
    price: 53,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '100GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '100GB hotspot', '5G Ultra Capacity speeds', 'Priority network access', 'Netflix Premium + Apple TV+', 'International roaming', 'No contract'],
  },
  {
    id: 'tm-magenta-premium-month',
    carrier: 'tmobile',
    name: 'Magenta Premium',
    price: 57,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '150GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '150GB hotspot', '5G Ultra Capacity speeds', 'Maximum network priority', 'All streaming services', 'Netflix Premium + Apple TV+', 'International roaming', 'No contract'],
    badge: 'PREMIUM',
  },
  
  // T-Mobile - Annual Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt)
  {
    id: 'tm-essentials-year',
    carrier: 'tmobile',
    name: 'Essentials (Annual)',
    price: 252,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '3GB',
    features: ['Unlimited 5G data', '3GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $252/year'],
  },
  {
    id: 'tm-magenta-year',
    carrier: 'tmobile',
    name: 'Magenta (Annual)',
    price: 288,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', 'Netflix Basic included', '5GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $288/year'],
  },
  {
    id: 'tm-magenta-max-year',
    carrier: 'tmobile',
    name: 'Magenta Max (Annual)',
    price: 336,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '40GB',
    features: ['Unlimited 5G data', 'Netflix Standard included', '40GB hotspot', 'Premium streaming', '4K video', 'Unlimited talk & text', 'No contract', 'Save $336/year'],
    badge: 'BEST VALUE',
  },

  // US Cellular - Monthly Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt)
  {
    id: 'usc-basic-month',
    carrier: 'uscellular',
    name: 'Basic Unlimited',
    price: 21,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'usc-everyday-month',
    carrier: 'uscellular',
    name: 'Everyday Unlimited',
    price: 22,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '15GB hotspot', 'Premium network access', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'usc-value-month',
    carrier: 'uscellular',
    name: 'Value Unlimited',
    price: 23,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '10GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '10GB hotspot', 'No contract'],
  },
  {
    id: 'usc-even-better-month',
    carrier: 'uscellular',
    name: 'Even Better Unlimited',
    price: 25,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '50GB hotspot', 'Premium network access', 'Premium streaming', 'Free streaming services', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'usc-best-unlimited-month',
    carrier: 'uscellular',
    name: 'Best Unlimited',
    price: 28,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '75GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '75GB hotspot', 'Premium network access', 'Premium streaming', 'Priority data', 'International features', 'No contract'],
  },
  {
    id: 'usc-ultra-unlimited-month',
    carrier: 'uscellular',
    name: 'Ultra Unlimited',
    price: 30,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '100GB',
    features: ['Unlimited 5G data', '4K video', 'Unlimited talk & text', '100GB hotspot', 'Premium network speeds', 'Premium streaming', 'Priority data', 'International features', 'No contract'],
  },
  {
    id: 'usc-premium-unlimited-month',
    carrier: 'uscellular',
    name: 'Premium Unlimited',
    price: 54,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '150GB',
    features: ['Unlimited 5G data', '4K video', 'Unlimited talk & text', '150GB hotspot', 'Maximum network speeds', 'Premium streaming', 'Priority data', 'International features', 'All streaming services', 'No contract'],
    badge: 'PREMIUM',
  },
  
  // US Cellular - Annual Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt)
  {
    id: 'usc-basic-year',
    carrier: 'uscellular',
    name: 'Basic Unlimited (Annual)',
    price: 252,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $252/year'],
  },
  {
    id: 'usc-everyday-year',
    carrier: 'uscellular',
    name: 'Everyday Unlimited (Annual)',
    price: 264,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', '15GB hotspot', 'Premium network access', 'Unlimited talk & text', 'No contract', 'Save $264/year'],
  },
  {
    id: 'usc-even-better-year',
    carrier: 'uscellular',
    name: 'Even Better Unlimited (Annual)',
    price: 300,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited 5G data', '50GB hotspot', 'Premium streaming', 'HD/4K video', 'Unlimited talk & text', 'No contract', 'Save $300/year'],
    badge: 'BEST VALUE',
  },

  // Mint Mobile - Monthly Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt, data limited)
  {
    id: 'mint-3gb-month',
    carrier: 'mintmobile',
    name: '3GB Plan',
    price: 9,
    period: 'month',
    data: '3GB',
    speed: '5G',
    hotspot: '3GB',
    features: ['3GB high-speed data', 'Unlimited talk & text', '3GB mobile hotspot'],
  },
  {
    id: 'mint-5gb-month',
    carrier: 'mintmobile',
    name: '5GB Plan',
    price: 10,
    period: 'month',
    data: '5GB',
    speed: '5G',
    hotspot: '5GB',
    features: ['5GB high-speed data', 'Unlimited talk & text', '5GB mobile hotspot', '5G included'],
  },
  {
    id: 'mint-10gb-month',
    carrier: 'mintmobile',
    name: '10GB Plan',
    price: 11,
    period: 'month',
    data: '10GB',
    speed: '5G',
    hotspot: '5GB',
    features: ['10GB high-speed data', 'Unlimited talk & text', '5GB mobile hotspot', '5G included'],
  },
  {
    id: 'mint-15gb-month',
    carrier: 'mintmobile',
    name: '15GB Plan',
    price: 12,
    period: 'month',
    data: '15GB',
    speed: '5G',
    hotspot: '10GB',
    features: ['15GB high-speed data', 'Unlimited talk & text', '10GB mobile hotspot', '5G included'],
  },
  {
    id: 'mint-20gb-month',
    carrier: 'mintmobile',
    name: '20GB Plan',
    price: 13,
    period: 'month',
    data: '20GB',
    speed: '5G',
    hotspot: '10GB',
    features: ['20GB high-speed data', 'Unlimited talk & text', '10GB mobile hotspot', '5G included'],
  },
  {
    id: 'mint-unlimited-month',
    carrier: 'mintmobile',
    name: 'Unlimited Plan',
    price: 14,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '10GB',
    features: ['Unlimited high-speed data', 'HD video streaming', 'Unlimited talk & text', '10GB mobile hotspot', '5G included', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'mint-unlimited-pro-month',
    carrier: 'mintmobile',
    name: 'Unlimited Pro',
    price: 16,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '20GB',
    features: ['Unlimited high-speed data', 'HD/4K video', 'Unlimited talk & text', '20GB hotspot', 'Premium network access', '5G included', 'No contract'],
  },
  {
    id: 'mint-unlimited-ultra-month',
    carrier: 'mintmobile',
    name: 'Unlimited Ultra',
    price: 18,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited high-speed data', 'HD/4K video', 'Unlimited talk & text', '50GB hotspot', 'Premium network speeds', 'Priority data', '5G included', 'No contract'],
  },
  {
    id: 'mint-unlimited-max-month',
    carrier: 'mintmobile',
    name: 'Unlimited Max',
    price: 40,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '100GB',
    features: ['Unlimited high-speed data', '4K video', 'Unlimited talk & text', '100GB hotspot', 'Maximum network speeds', 'Priority data', 'International features', '5G included', 'All streaming services', 'No contract'],
    badge: 'PREMIUM',
  },
  
  // Mint Mobile - Annual Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt)
  {
    id: 'mint-5gb-year',
    carrier: 'mintmobile',
    name: '5GB Plan (12 months)',
    price: 60,
    period: 'year',
    data: '5GB',
    speed: '5G',
    hotspot: '5GB',
    features: ['5GB high-speed data', '5G included', 'Save $60/year', '5GB mobile hotspot'],
  },
  {
    id: 'mint-15gb-year',
    carrier: 'mintmobile',
    name: '15GB Plan (12 months)',
    price: 84,
    period: 'year',
    data: '15GB',
    speed: '5G',
    hotspot: '10GB',
    features: ['15GB high-speed data', '5G included', 'Save $84/year', '10GB mobile hotspot'],
  },
  {
    id: 'mint-20gb-year',
    carrier: 'mintmobile',
    name: '20GB Plan (12 months)',
    price: 108,
    period: 'year',
    data: '20GB',
    speed: '5G',
    hotspot: '10GB',
    features: ['20GB high-speed data', '5G included', 'Save $108/year', '10GB mobile hotspot'],
  },
  {
    id: 'mint-unlimited-year',
    carrier: 'mintmobile',
    name: 'Unlimited Plan (12 months)',
    price: 120,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '10GB',
    features: ['Unlimited high-speed data', '5G included', 'Save $120/year', '10GB mobile hotspot'],
    badge: 'BEST VALUE',
  },
  {
    id: 'mint-unlimited-pro-year',
    carrier: 'mintmobile',
    name: 'Unlimited Pro (12 months)',
    price: 144,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '20GB',
    features: ['Unlimited high-speed data', '20GB hotspot', 'Save $144/year', 'Premium network'],
  },

  // Cricket Wireless - Monthly Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt)
  {
    id: 'cricket-basic-month',
    carrier: 'cricket',
    name: 'Cricket Basic',
    price: 20,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'cricket-core-month',
    carrier: 'cricket',
    name: 'Cricket Core',
    price: 21,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '5GB hotspot', 'No contract'],
  },
  {
    id: 'cricket-more-month',
    carrier: 'cricket',
    name: 'Cricket More',
    price: 23,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '15GB hotspot', 'Premium network access', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'cricket-most-month',
    carrier: 'cricket',
    name: 'Cricket Most',
    price: 25,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '50GB hotspot', 'Premium network access', 'Premium streaming', 'Max speeds', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'cricket-max-month',
    carrier: 'cricket',
    name: 'Cricket Max',
    price: 24,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '75GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '75GB hotspot', 'Premium network access', 'Premium streaming', 'Priority data', 'International features', 'No contract'],
  },
  {
    id: 'cricket-ultra-month',
    carrier: 'cricket',
    name: 'Cricket Ultra',
    price: 26,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '100GB',
    features: ['Unlimited 5G data', '4K video', 'Unlimited talk & text', '100GB hotspot', 'Premium network speeds', 'Premium streaming', 'Priority data', 'International features', 'No contract'],
  },
  {
    id: 'cricket-premium-month',
    carrier: 'cricket',
    name: 'Cricket Premium',
    price: 51,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '150GB',
    features: ['Unlimited 5G data', '4K video', 'Unlimited talk & text', '150GB hotspot', 'Maximum network speeds', 'Premium streaming', 'Priority data', 'International features', 'All streaming services', 'No contract'],
    badge: 'PREMIUM',
  },
  
  // Cricket Wireless - Annual Plans (Giá rẻ hơn 55%, sắp xếp từ rẻ đến đắt)
  {
    id: 'cricket-core-year',
    carrier: 'cricket',
    name: 'Cricket Core (Annual)',
    price: 252,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', '5GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $252/year'],
  },
  {
    id: 'cricket-more-year',
    carrier: 'cricket',
    name: 'Cricket More (Annual)',
    price: 264,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', '15GB hotspot', 'Premium network access', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $264/year'],
  },
  {
    id: 'cricket-most-year',
    carrier: 'cricket',
    name: 'Cricket Most (Annual)',
    price: 264,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited 5G data', '50GB hotspot', 'Premium streaming', 'HD/4K video', 'Max speeds', 'Unlimited talk & text', 'No contract', 'Save $264/year'],
    badge: 'BEST VALUE',
  },
];