import { Package } from '@/types';

export const defaultPackages: Package[] = [
  // Verizon - Monthly Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'vz-basic-5g-month',
    carrier: 'verizon',
    name: 'Basic 5G',
    price: 43,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'vz-5g-start-month',
    carrier: 'verizon',
    name: '5G Start (25GB Hotspot)',
    price: 44,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '45GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '45GB hotspot', 'No contract'],
  },
  {
    id: 'vz-5g-play-month',
    carrier: 'verizon',
    name: '5G Play More (45GB Hotspot)',
    price: 46,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '65GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '65GB hotspot', 'Premium network access', 'Disney+, Hulu, ESPN+ included', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'vz-5g-do-more-month',
    carrier: 'verizon',
    name: '5G Do More (50GB Hotspot)',
    price: 47,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '70GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '70GB hotspot', 'Premium network access', '50% off connected devices', 'No contract'],
  },
  {
    id: 'vz-5g-pro-month',
    carrier: 'verizon',
    name: '5G Pro (60GB Hotspot)',
    price: 49,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '80GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '80GB hotspot', 'Premium network access', 'Priority data', 'No contract'],
  },
  {
    id: 'vz-5g-get-more-month',
    carrier: 'verizon',
    name: '5G Get More (70GB Hotspot)',
    price: 50,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '90GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '90GB hotspot', 'Premium network access', 'Priority data', 'Disney+, Hulu, ESPN+ included', 'Apple Music included', 'Premium streaming', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'vz-5g-premium-month',
    carrier: 'verizon',
    name: '5G Premium (95GB Hotspot)',
    price: 73,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '115GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '115GB hotspot', '5G Ultra Wideband speeds', 'Premium network priority', 'All streaming services', 'International roaming', 'No contract'],
  },
  {
    id: 'vz-5g-ultra-month',
    carrier: 'verizon',
    name: '5G Ultra (120GB Hotspot)',
    price: 74,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '140GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '140GB hotspot', '5G Ultra Wideband speeds', 'Maximum network priority', 'All streaming services', 'International roaming', 'No contract'],
  },
  {
    id: 'vz-5g-max-month',
    carrier: 'verizon',
    name: '5G Max (170GB Hotspot)',
    price: 76,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '190GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '190GB hotspot', '5G Ultra Wideband speeds', 'Ultra-fast speeds', 'Maximum network priority', 'All streaming services', 'International roaming', 'Premium network priority', 'No contract'],
    badge: 'PREMIUM',
  },

  // Verizon - Annual Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'vz-basic-5g-year',
    carrier: 'verizon',
    name: 'Basic 5G (Annual)',
    price: 272,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', 'No contract', 'Save $252/year'],
  },
  {
    id: 'vz-5g-start-year',
    carrier: 'verizon',
    name: '5G Start (Annual - 25GB Hotspot)',
    price: 308,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '45GB',
    features: ['Unlimited 5G data', 'HD video streaming', '45GB hotspot', 'Unlimited talk & text', 'No contract', 'Save $288/year'],
  },
  {
    id: 'vz-5g-play-year',
    carrier: 'verizon',
    name: '5G Play More (Annual - 45GB Hotspot)',
    price: 332,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '65GB',
    features: ['Unlimited 5G data', 'Premium network access', 'Disney+, Hulu, ESPN+ included', '65GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $312/year'],
  },
  {
    id: 'vz-5g-get-more-year',
    carrier: 'verizon',
    name: '5G Get More (Annual - 70GB Hotspot)',
    price: 380,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '90GB',
    features: ['Unlimited 5G data', '90GB hotspot', 'Disney+, Hulu, ESPN+ included', 'Apple Music included', 'Premium streaming', 'HD/4K video', 'Unlimited talk & text', 'No contract', 'Save $360/year'],
    badge: 'BEST VALUE',
  },

  // Att - Monthly Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'att-basic-month',
    carrier: 'att',
    name: 'Basic Plan',
    price: 38,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'att-unlimited-starter-month',
    carrier: 'att',
    name: 'Unlimited Starter (25GB Hotspot)',
    price: 39,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '45GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '45GB hotspot', 'No contract'],
  },
  {
    id: 'att-value-plus-month',
    carrier: 'att',
    name: 'Value Plus (23GB Hotspot)',
    price: 40,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '43GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '43GB hotspot', 'No contract'],
  },
  {
    id: 'att-unlimited-extra-month',
    carrier: 'att',
    name: 'Unlimited Extra (35GB Hotspot)',
    price: 42,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '55GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '55GB hotspot', 'Premium network access', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'att-unlimited-pro-month',
    carrier: 'att',
    name: 'Unlimited Pro (50GB Hotspot)',
    price: 46,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '70GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '70GB hotspot', 'Premium network access', 'Priority data', 'No contract'],
  },
  {
    id: 'att-unlimited-elite-month',
    carrier: 'att',
    name: 'Unlimited Elite (60GB Hotspot)',
    price: 47,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '80GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '80GB hotspot', 'Premium network access', 'Priority data', 'HBO Max included', 'Premium streaming', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'att-unlimited-max-month',
    carrier: 'att',
    name: 'Unlimited Max (80GB Hotspot)',
    price: 70,
    period: 'month',
    data: 'Unlimited',
    speed: '5G+',
    hotspot: '100GB',
    features: ['Unlimited 5G+ data', '4K video', 'Unlimited talk & text', '100GB hotspot', '5G+ speeds available', 'Premium network priority', 'HBO Max + Netflix', 'International roaming', 'No contract'],
  },
  {
    id: 'att-unlimited-ultra-month',
    carrier: 'att',
    name: 'Unlimited Ultra (120GB Hotspot)',
    price: 73,
    period: 'month',
    data: 'Unlimited',
    speed: '5G+',
    hotspot: '140GB',
    features: ['Unlimited 5G+ data', '4K video', 'Unlimited talk & text', '140GB hotspot', '5G+ Ultra speeds', 'Priority network access', 'HBO Max + Netflix', 'International roaming', 'No contract'],
  },
  {
    id: 'att-unlimited-premium-month',
    carrier: 'att',
    name: 'Unlimited Premium (170GB Hotspot)',
    price: 75,
    period: 'month',
    data: 'Unlimited',
    speed: '5G+',
    hotspot: '190GB',
    features: ['Unlimited 5G+ data', '4K video', 'Unlimited talk & text', '190GB hotspot', '5G+ Ultra speeds', 'Maximum network priority', 'All streaming services', 'HBO Max + Netflix', 'International roaming', 'No contract'],
    badge: 'PREMIUM',
  },

  // Att - Annual Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'att-value-plus-year',
    carrier: 'att',
    name: 'Value Plus (Annual - 23GB Hotspot)',
    price: 260,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '43GB',
    features: ['Unlimited 5G data', '43GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $240/year'],
  },
  {
    id: 'att-unlimited-starter-year',
    carrier: 'att',
    name: 'Unlimited Starter (25GB Hotspot - Annual)',
    price: 248,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '45GB',
    features: ['Unlimited 5G data', '45GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $228/year'],
  },
  {
    id: 'att-unlimited-extra-year',
    carrier: 'att',
    name: 'Unlimited Extra (35GB Hotspot - Annual)',
    price: 284,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '55GB',
    features: ['Unlimited 5G data', '55GB hotspot', 'Premium network access', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $264/year'],
  },
  {
    id: 'att-unlimited-elite-year',
    carrier: 'att',
    name: 'Unlimited Elite (60GB Hotspot - Annual)',
    price: 320,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '80GB',
    features: ['Unlimited 5G data', '80GB hotspot', 'HBO Max included', 'Premium streaming', 'HD/4K video', 'Unlimited talk & text', 'No contract', 'Save $300/year'],
    badge: 'BEST VALUE',
  },

  // T Mobile - Monthly Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'tm-basic-month',
    carrier: 'tmobile',
    name: 'Basic 5G',
    price: 41,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'tm-essentials-month',
    carrier: 'tmobile',
    name: 'Essentials (23GB Hotspot)',
    price: 43,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '43GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '43GB hotspot', 'No contract'],
  },
  {
    id: 'tm-magenta-month',
    carrier: 'tmobile',
    name: 'Magenta (25GB Hotspot)',
    price: 44,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '45GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '45GB hotspot', 'Netflix Basic included', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'tm-magenta-plus-month',
    carrier: 'tmobile',
    name: 'Magenta Plus (40GB Hotspot)',
    price: 46,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '60GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '60GB hotspot', 'Netflix Basic included', 'Premium network access', 'No contract'],
  },
  {
    id: 'tm-magenta-max-month',
    carrier: 'tmobile',
    name: 'Magenta Max (60GB Hotspot)',
    price: 48,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '80GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '80GB hotspot', 'Premium network access', 'Netflix Standard included', 'Premium streaming', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'tm-magenta-ultra-month',
    carrier: 'tmobile',
    name: 'Magenta Ultra (80GB Hotspot)',
    price: 71,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '100GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '100GB hotspot', '5G Ultra Capacity speeds', 'Premium network priority', 'Netflix Premium + Apple TV+', 'International roaming', 'No contract'],
  },
  {
    id: 'tm-magenta-extreme-month',
    carrier: 'tmobile',
    name: 'Magenta Extreme (120GB Hotspot)',
    price: 73,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '140GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '140GB hotspot', '5G Ultra Capacity speeds', 'Priority network access', 'Netflix Premium + Apple TV+', 'International roaming', 'No contract'],
  },
  {
    id: 'tm-magenta-premium-month',
    carrier: 'tmobile',
    name: 'Magenta Premium (170GB Hotspot)',
    price: 77,
    period: 'month',
    data: 'Unlimited',
    speed: '5G Ultra',
    hotspot: '190GB',
    features: ['Unlimited 5G Ultra data', '4K video', 'Unlimited talk & text', '190GB hotspot', '5G Ultra Capacity speeds', 'Maximum network priority', 'All streaming services', 'Netflix Premium + Apple TV+', 'International roaming', 'No contract'],
    badge: 'PREMIUM',
  },

  // T Mobile - Annual Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'tm-essentials-year',
    carrier: 'tmobile',
    name: 'Essentials (Annual - 23GB Hotspot)',
    price: 272,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '43GB',
    features: ['Unlimited 5G data', '43GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $252/year'],
  },
  {
    id: 'tm-magenta-year',
    carrier: 'tmobile',
    name: 'Magenta (Annual - 25GB Hotspot)',
    price: 308,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '45GB',
    features: ['Unlimited 5G data', 'Netflix Basic included', '45GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $288/year'],
  },
  {
    id: 'tm-magenta-max-year',
    carrier: 'tmobile',
    name: 'Magenta Max (Annual - 60GB Hotspot)',
    price: 356,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '80GB',
    features: ['Unlimited 5G data', 'Netflix Standard included', '80GB hotspot', 'Premium streaming', '4K video', 'Unlimited talk & text', 'No contract', 'Save $336/year'],
    badge: 'BEST VALUE',
  },

  // Us Cellular - Monthly Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'usc-basic-month',
    carrier: 'uscellular',
    name: 'Basic Unlimited',
    price: 41,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'usc-everyday-month',
    carrier: 'uscellular',
    name: 'Everyday Unlimited (35GB Hotspot)',
    price: 42,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '55GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '55GB hotspot', 'Premium network access', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'usc-value-month',
    carrier: 'uscellular',
    name: 'Value Unlimited (30GB Hotspot)',
    price: 43,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '50GB hotspot', 'No contract'],
  },
  {
    id: 'usc-even-better-month',
    carrier: 'uscellular',
    name: 'Even Better Unlimited (70GB Hotspot)',
    price: 45,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '90GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '90GB hotspot', 'Premium network access', 'Premium streaming', 'Free streaming services', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'usc-best-unlimited-month',
    carrier: 'uscellular',
    name: 'Best Unlimited (95GB Hotspot)',
    price: 48,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '115GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '115GB hotspot', 'Premium network access', 'Premium streaming', 'Priority data', 'International features', 'No contract'],
  },
  {
    id: 'usc-ultra-unlimited-month',
    carrier: 'uscellular',
    name: 'Ultra Unlimited (120GB Hotspot)',
    price: 50,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '140GB',
    features: ['Unlimited 5G data', '4K video', 'Unlimited talk & text', '140GB hotspot', 'Premium network speeds', 'Premium streaming', 'Priority data', 'International features', 'No contract'],
  },
  {
    id: 'usc-premium-unlimited-month',
    carrier: 'uscellular',
    name: 'Premium Unlimited (170GB Hotspot)',
    price: 74,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '190GB',
    features: ['Unlimited 5G data', '4K video', 'Unlimited talk & text', '190GB hotspot', 'Maximum network speeds', 'Premium streaming', 'Priority data', 'International features', 'All streaming services', 'No contract'],
    badge: 'PREMIUM',
  },

  // Us Cellular - Annual Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'usc-basic-year',
    carrier: 'uscellular',
    name: 'Basic Unlimited (Annual)',
    price: 272,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $252/year'],
  },
  {
    id: 'usc-everyday-year',
    carrier: 'uscellular',
    name: 'Everyday Unlimited (35GB Hotspot - Annual)',
    price: 284,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '55GB',
    features: ['Unlimited 5G data', '55GB hotspot', 'Premium network access', 'Unlimited talk & text', 'No contract', 'Save $264/year'],
  },
  {
    id: 'usc-even-better-year',
    carrier: 'uscellular',
    name: 'Even Better Unlimited (70GB Hotspot - Annual)',
    price: 320,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '90GB',
    features: ['Unlimited 5G data', '90GB hotspot', 'Premium streaming', 'HD/4K video', 'Unlimited talk & text', 'No contract', 'Save $300/year'],
    badge: 'BEST VALUE',
  },

  // Mint Mobile - Monthly Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'mint-3gb-month',
    carrier: 'mintmobile',
    name: '43GB Plan',
    price: 29,
    period: 'month',
    data: '43GB',
    speed: '5G',
    hotspot: '43GB',
    features: ['43GB high-speed data', 'Unlimited talk & text', '43GB mobile hotspot'],
  },
  {
    id: 'mint-5gb-month',
    carrier: 'mintmobile',
    name: '45GB Plan',
    price: 30,
    period: 'month',
    data: '45GB',
    speed: '5G',
    hotspot: '45GB',
    features: ['45GB high-speed data', 'Unlimited talk & text', '45GB mobile hotspot', '5G included'],
  },
  {
    id: 'mint-10gb-month',
    carrier: 'mintmobile',
    name: '50GB Plan',
    price: 31,
    period: 'month',
    data: '50GB',
    speed: '5G',
    hotspot: '45GB',
    features: ['50GB high-speed data', 'Unlimited talk & text', '45GB mobile hotspot', '5G included'],
  },
  {
    id: 'mint-15gb-month',
    carrier: 'mintmobile',
    name: '55GB Plan',
    price: 32,
    period: 'month',
    data: '55GB',
    speed: '5G',
    hotspot: '50GB',
    features: ['55GB high-speed data', 'Unlimited talk & text', '50GB mobile hotspot', '5G included'],
  },
  {
    id: 'mint-20gb-month',
    carrier: 'mintmobile',
    name: '60GB Plan',
    price: 33,
    period: 'month',
    data: '60GB',
    speed: '5G',
    hotspot: '50GB',
    features: ['60GB high-speed data', 'Unlimited talk & text', '50GB mobile hotspot', '5G included'],
  },
  {
    id: 'mint-unlimited-month',
    carrier: 'mintmobile',
    name: 'Unlimited Plan (30GB Hotspot)',
    price: 34,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited high-speed data', 'HD video streaming', 'Unlimited talk & text', '50GB mobile hotspot', '5G included', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'mint-unlimited-pro-month',
    carrier: 'mintmobile',
    name: 'Unlimited Pro (40GB Hotspot)',
    price: 36,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '60GB',
    features: ['Unlimited high-speed data', 'HD/4K video', 'Unlimited talk & text', '60GB hotspot', 'Premium network access', '5G included', 'No contract'],
  },
  {
    id: 'mint-unlimited-ultra-month',
    carrier: 'mintmobile',
    name: 'Unlimited Ultra (70GB Hotspot)',
    price: 38,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '90GB',
    features: ['Unlimited high-speed data', 'HD/4K video', 'Unlimited talk & text', '90GB hotspot', 'Premium network speeds', 'Priority data', '5G included', 'No contract'],
  },
  {
    id: 'mint-unlimited-max-month',
    carrier: 'mintmobile',
    name: 'Unlimited Max (120GB Hotspot)',
    price: 60,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '140GB',
    features: ['Unlimited high-speed data', '4K video', 'Unlimited talk & text', '140GB hotspot', 'Maximum network speeds', 'Priority data', 'International features', '5G included', 'All streaming services', 'No contract'],
    badge: 'PREMIUM',
  },

  // Mint Mobile - Annual Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'mint-5gb-year',
    carrier: 'mintmobile',
    name: '45GB Plan (12 months)',
    price: 80,
    period: 'year',
    data: '45GB',
    speed: '5G',
    hotspot: '45GB',
    features: ['45GB high-speed data', '5G included', 'Save $60/year', '45GB mobile hotspot'],
  },
  {
    id: 'mint-15gb-year',
    carrier: 'mintmobile',
    name: '55GB Plan (12 months)',
    price: 104,
    period: 'year',
    data: '55GB',
    speed: '5G',
    hotspot: '50GB',
    features: ['55GB high-speed data', '5G included', 'Save $84/year', '50GB mobile hotspot'],
  },
  {
    id: 'mint-20gb-year',
    carrier: 'mintmobile',
    name: '60GB Plan (12 months)',
    price: 128,
    period: 'year',
    data: '60GB',
    speed: '5G',
    hotspot: '50GB',
    features: ['60GB high-speed data', '5G included', 'Save $108/year', '50GB mobile hotspot'],
  },
  {
    id: 'mint-unlimited-year',
    carrier: 'mintmobile',
    name: 'Unlimited Plan (30GB Hotspot - 12 months)',
    price: 140,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited high-speed data', '5G included', 'Save $120/year', '50GB mobile hotspot'],
    badge: 'BEST VALUE',
  },
  {
    id: 'mint-unlimited-pro-year',
    carrier: 'mintmobile',
    name: 'Unlimited Pro (40GB Hotspot - 12 months)',
    price: 164,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '60GB',
    features: ['Unlimited high-speed data', '60GB hotspot', 'Save $144/year', 'Premium network'],
  },

  // Cricket - Monthly Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'cricket-basic-month',
    carrier: 'cricket',
    name: 'Cricket Basic',
    price: 40,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'cricket-core-month',
    carrier: 'cricket',
    name: 'Cricket Core (25GB Hotspot)',
    price: 41,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '45GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '45GB hotspot', 'No contract'],
  },
  {
    id: 'cricket-more-month',
    carrier: 'cricket',
    name: 'Cricket More (35GB Hotspot)',
    price: 43,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '55GB',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', '55GB hotspot', 'Premium network access', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'cricket-most-month',
    carrier: 'cricket',
    name: 'Cricket Most (70GB Hotspot)',
    price: 45,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '90GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '90GB hotspot', 'Premium network access', 'Premium streaming', 'Max speeds', 'No contract'],
    badge: 'BEST VALUE',
  },
  {
    id: 'cricket-max-month',
    carrier: 'cricket',
    name: 'Cricket Max (95GB Hotspot)',
    price: 44,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '115GB',
    features: ['Unlimited 5G data', 'HD/4K video', 'Unlimited talk & text', '115GB hotspot', 'Premium network access', 'Premium streaming', 'Priority data', 'International features', 'No contract'],
  },
  {
    id: 'cricket-ultra-month',
    carrier: 'cricket',
    name: 'Cricket Ultra (120GB Hotspot)',
    price: 46,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '140GB',
    features: ['Unlimited 5G data', '4K video', 'Unlimited talk & text', '140GB hotspot', 'Premium network speeds', 'Premium streaming', 'Priority data', 'International features', 'No contract'],
  },
  {
    id: 'cricket-premium-month',
    carrier: 'cricket',
    name: 'Cricket Premium (170GB Hotspot)',
    price: 71,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '190GB',
    features: ['Unlimited 5G data', '4K video', 'Unlimited talk & text', '190GB hotspot', 'Maximum network speeds', 'Premium streaming', 'Priority data', 'International features', 'All streaming services', 'No contract'],
    badge: 'PREMIUM',
  },

  // Cricket - Annual Plans (Giá rẻ hơn 55% so với giá thật, sắp xếp từ rẻ đến đắt)
  {
    id: 'cricket-core-year',
    carrier: 'cricket',
    name: 'Cricket Core (Annual - 25GB Hotspot)',
    price: 272,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '45GB',
    features: ['Unlimited 5G data', '45GB hotspot', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $252/year'],
  },
  {
    id: 'cricket-more-year',
    carrier: 'cricket',
    name: 'Cricket More (Annual - 35GB Hotspot)',
    price: 284,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '55GB',
    features: ['Unlimited 5G data', '55GB hotspot', 'Premium network access', 'HD streaming', 'Unlimited talk & text', 'No contract', 'Save $264/year'],
  },
  {
    id: 'cricket-most-year',
    carrier: 'cricket',
    name: 'Cricket Most (Annual - 70GB Hotspot)',
    price: 284,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '90GB',
    features: ['Unlimited 5G data', '90GB hotspot', 'Premium streaming', 'HD/4K video', 'Max speeds', 'Unlimited talk & text', 'No contract', 'Save $264/year'],
    badge: 'BEST VALUE',
  },

];
