import { Package } from '@/types';

export const defaultPackages: Package[] = [
  // Verizon - Monthly Plans
  {
    id: 'vz-5g-start-month',
    carrier: 'verizon',
    name: '5G Start',
    price: 46,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', 'No contract', 'Premium network access'],
  },
  {
    id: 'vz-5g-play-month',
    carrier: 'verizon',
    name: '5G Play More',
    price: 52,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '25GB',
    features: ['Unlimited 5G data', 'Premium network access', 'Disney+, Hulu, ESPN+ included', '25GB hotspot', 'HD streaming'],
    badge: 'POPULAR',
  },
  {
    id: 'vz-5g-do-more-month',
    carrier: 'verizon',
    name: '5G Do More',
    price: 52,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '25GB',
    features: ['Unlimited 5G data', '25GB hotspot', '50% off connected devices', 'Premium network access', 'HD streaming'],
  },
  {
    id: 'vz-5g-get-more-month',
    carrier: 'verizon',
    name: '5G Get More',
    price: 59,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited 5G data', '50GB hotspot', 'Disney+, Hulu, ESPN+ included', 'Apple Music included', 'Premium streaming'],
    badge: 'BEST VALUE',
  },
  // Verizon - Annual Plans
  {
    id: 'vz-5g-start-year',
    carrier: 'verizon',
    name: '5G Start (Annual)',
    price: 546,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', 'No contract', 'Save $546/year'],
  },
  {
    id: 'vz-5g-play-year',
    carrier: 'verizon',
    name: '5G Play More (Annual)',
    price: 624,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '25GB',
    features: ['Unlimited 5G data', 'Disney+, Hulu, ESPN+ included', '25GB hotspot', 'Save $624/year'],
  },

  // AT&T - Monthly Plans
  {
    id: 'att-value-plus-month',
    carrier: 'att',
    name: 'Value Plus',
    price: 33,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'HD video streaming', 'Unlimited talk & text', 'No contract'],
  },
  {
    id: 'att-unlimited-starter-month',
    carrier: 'att',
    name: 'Unlimited Starter',
    price: 42,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', '5GB hotspot', 'HD video streaming', 'Unlimited talk & text'],
  },
  {
    id: 'att-unlimited-extra-month',
    carrier: 'att',
    name: 'Unlimited Extra',
    price: 49,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', '15GB hotspot', 'Premium network access', 'HD streaming', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'att-unlimited-elite-month',
    carrier: 'att',
    name: 'Unlimited Elite',
    price: 55,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '40GB',
    features: ['Unlimited 5G data', '40GB hotspot', 'HBO Max included', 'Premium streaming', 'HD/4K video'],
    badge: 'BEST VALUE',
  },
  // AT&T - Annual Plans
  {
    id: 'att-unlimited-starter-year',
    carrier: 'att',
    name: 'Unlimited Starter (Annual)',
    price: 507,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', '5GB hotspot', 'Save $507/year', 'HD streaming'],
  },
  {
    id: 'att-unlimited-extra-year',
    carrier: 'att',
    name: 'Unlimited Extra (Annual)',
    price: 585,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', '15GB hotspot', 'Save $585/year', 'Premium network'],
  },

  // T-Mobile - Monthly Plans
  {
    id: 'tm-essentials-month',
    carrier: 'tmobile',
    name: 'Essentials',
    price: 39,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '3GB',
    features: ['Unlimited 5G data', '3GB hotspot', 'Unlimited talk & text', 'HD streaming'],
  },
  {
    id: 'tm-magenta-month',
    carrier: 'tmobile',
    name: 'Magenta',
    price: 46,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', '5GB hotspot', 'Netflix Basic included', 'Unlimited talk & text', 'HD streaming'],
    badge: 'POPULAR',
  },
  {
    id: 'tm-magenta-max-month',
    carrier: 'tmobile',
    name: 'Magenta Max',
    price: 55,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '40GB',
    features: ['Unlimited 5G data', '40GB hotspot', 'Netflix Standard included', 'Premium streaming', '4K video'],
    badge: 'BEST VALUE',
  },
  // T-Mobile - Annual Plans
  {
    id: 'tm-magenta-year',
    carrier: 'tmobile',
    name: 'Magenta (Annual)',
    price: 546,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '5GB',
    features: ['Unlimited 5G data', 'Netflix Basic included', 'Save $546/year', '5GB hotspot'],
  },
  {
    id: 'tm-magenta-max-year',
    carrier: 'tmobile',
    name: 'Magenta Max (Annual)',
    price: 663,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '40GB',
    features: ['Unlimited 5G data', 'Netflix Standard included', '40GB hotspot', 'Save $663/year'],
  },

  // US Cellular - Monthly Plans
  {
    id: 'usc-basic-month',
    carrier: 'uscellular',
    name: 'Basic Unlimited',
    price: 36,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract', 'HD streaming'],
  },
  {
    id: 'usc-everyday-month',
    carrier: 'uscellular',
    name: 'Everyday Unlimited',
    price: 42,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', '15GB hotspot', 'Premium network access', 'Unlimited talk & text'],
    badge: 'POPULAR',
  },
  {
    id: 'usc-even-better-month',
    carrier: 'uscellular',
    name: 'Even Better Unlimited',
    price: 49,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited 5G data', '50GB hotspot', 'Premium streaming', 'HD/4K video', 'Free streaming services'],
    badge: 'BEST VALUE',
  },
  // US Cellular - Annual Plans
  {
    id: 'usc-everyday-year',
    carrier: 'uscellular',
    name: 'Everyday Unlimited (Annual)',
    price: 507,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', '15GB hotspot', 'Save $507/year', 'Premium network'],
  },

  // Mint Mobile - Monthly Plans
  {
    id: 'mint-5gb-month',
    carrier: 'mintmobile',
    name: '5GB Plan',
    price: 10,
    period: 'month',
    data: '5GB',
    speed: '5G',
    hotspot: '5GB',
    features: ['5GB high-speed data', '5G included', 'Unlimited talk & text', '5GB mobile hotspot'],
  },
  {
    id: 'mint-15gb-month',
    carrier: 'mintmobile',
    name: '15GB Plan',
    price: 16,
    period: 'month',
    data: '15GB',
    speed: '5G',
    hotspot: '5GB',
    features: ['15GB high-speed data', '5G included', 'Unlimited talk & text', '5GB mobile hotspot'],
  },
  {
    id: 'mint-20gb-month',
    carrier: 'mintmobile',
    name: '20GB Plan',
    price: 20,
    period: 'month',
    data: '20GB',
    speed: '5G',
    hotspot: '10GB',
    features: ['20GB high-speed data', '5G included', 'Unlimited talk & text', '10GB mobile hotspot'],
  },
  {
    id: 'mint-unlimited-month',
    carrier: 'mintmobile',
    name: 'Unlimited Plan',
    price: 23,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '10GB',
    features: ['Unlimited high-speed data', '5G included', 'Unlimited talk & text', '10GB mobile hotspot', 'HD streaming'],
    badge: 'BEST VALUE',
  },
  // Mint Mobile - Annual Plans (3 months minimum, 12 months best value)
  {
    id: 'mint-5gb-year',
    carrier: 'mintmobile',
    name: '5GB Plan (12 months)',
    price: 117,
    period: 'year',
    data: '5GB',
    speed: '5G',
    hotspot: '5GB',
    features: ['5GB high-speed data', '5G included', 'Save $117/year', '5GB mobile hotspot'],
  },
  {
    id: 'mint-15gb-year',
    carrier: 'mintmobile',
    name: '15GB Plan (12 months)',
    price: 195,
    period: 'year',
    data: '15GB',
    speed: '5G',
    hotspot: '5GB',
    features: ['15GB high-speed data', '5G included', 'Save $195/year', '5GB mobile hotspot'],
  },
  {
    id: 'mint-20gb-year',
    carrier: 'mintmobile',
    name: '20GB Plan (12 months)',
    price: 234,
    period: 'year',
    data: '20GB',
    speed: '5G',
    hotspot: '10GB',
    features: ['20GB high-speed data', '5G included', 'Save $234/year', '10GB mobile hotspot'],
  },
  {
    id: 'mint-unlimited-year',
    carrier: 'mintmobile',
    name: 'Unlimited Plan (12 months)',
    price: 273,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '10GB',
    features: ['Unlimited high-speed data', '5G included', 'Save $273/year', '10GB mobile hotspot'],
    badge: 'BEST VALUE',
  },

  // Cricket Wireless - Monthly Plans
  {
    id: 'cricket-core-month',
    carrier: 'cricket',
    name: 'Cricket Core',
    price: 36,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: 'None',
    features: ['Unlimited 5G data', 'Unlimited talk & text', 'No contract', 'HD streaming'],
  },
  {
    id: 'cricket-more-month',
    carrier: 'cricket',
    name: 'Cricket More',
    price: 39,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', '15GB hotspot', 'Premium network access', 'HD streaming', 'No contract'],
    badge: 'POPULAR',
  },
  {
    id: 'cricket-most-month',
    carrier: 'cricket',
    name: 'Cricket Most',
    price: 42,
    period: 'month',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '50GB',
    features: ['Unlimited 5G data', '50GB hotspot', 'Premium streaming', 'HD/4K video', 'Max speeds'],
    badge: 'BEST VALUE',
  },
  // Cricket Wireless - Annual Plans
  {
    id: 'cricket-more-year',
    carrier: 'cricket',
    name: 'Cricket More (Annual)',
    price: 468,
    period: 'year',
    data: 'Unlimited',
    speed: '5G',
    hotspot: '15GB',
    features: ['Unlimited 5G data', '15GB hotspot', 'Save $468/year', 'Premium network'],
  },
];
